services:
    stems.core.pagination:
        class: Stems\CoreBundle\Service\Pagination

    stems.core.googlemap:
        class: Stems\CoreBundle\Service\GoogleMap

    stems.core.scrape:
        class: Stems\CoreBundle\Service\Scrape

    stems.core.twig.core_extension:
            class: Stems\CoreBundle\Twig\CoreExtension
            arguments: 
                em: "@doctrine.orm.entity_manager"
            tags:
                - { name: twig.extension }

    stems.core.front_listener:
        class: Stems\CoreBundle\EventListener\FrontListener
        arguments: 
            em: "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }