services:
    stems.core.bundles.management:
        class: Stems\CoreBundle\Service\BundleManagementService
        arguments: 
            bundles: %kernel.bundles%

    stems.core.sections.manager:
        class: Stems\CoreBundle\Service\SectionManagementService
        arguments: 
            em:          "@doctrine.orm.entity_manager"
            twig:        "@templating"
            formFactory: "@form.factory"
            types:       %stems.sections.available%

    stems.core.pagination:
        class: Stems\CoreBundle\Service\Pagination

    stems.core.googlemap:
        class: Stems\CoreBundle\Service\GoogleMap

    stems.core.scrape:
        class: Stems\CoreBundle\Service\Scrape

    stems.core.twig.core_extension:
            class: Stems\CoreBundle\Twig\CoreExtension
            arguments: 
                container: "@service_container"
                em: "@doctrine.orm.entity_manager"
            tags:
                - { name: twig.extension }

    stems.core.listener.base:
        class: Stems\CoreBundle\EventListener\BaseListener
        arguments: 
            em: "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }